project:
  type: website 
  output-dir: ../docs


website:
  title: "Activity-Driven Enhancement of Complex Fluids"
  page-navigation: true
  back-to-top-navigation: true
  sidebar:
    smooth-scroll: true
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Overview 
      - log.qmd 
      - tasks.qmd
      - links.qmd


format:
  html:
    theme: cosmo
    grid:
      sidebar-width: 305px
    toc: true
    # number-chapters: true
    # number-sections: true

execute:
  freeze: auto